name: dart_js_interop

environment:
  sdk: ">=2.0.0-dev.63.0 <3.0.0"

dependencies:
  js: "0.6.1+1"

dev_dependencies:
  build_runner: "0.10.1"
  build_test: "0.10.3+1"
  build_web_compilers: "0.4.2+1"
  test: "1.3.0"
